services:
  wallet-jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: wallet-jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - wallet_jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - wallet-jenkins-network
    restart: unless-stopped

  wallet-docker-dind:
    image: docker:dind
    privileged: true
    container_name: wallet-docker-dind
    volumes:
      - wallet_docker_data:/var/lib/docker
    environment:
      - DOCKER_TLS_CERTDIR=
    networks:
      - wallet-jenkins-network
    restart: unless-stopped

  wallet-nginx:
    image: nginx:alpine
    container_name: wallet-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/jenkins.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wallet-jenkins
    networks:
      - wallet-jenkins-network
    restart: unless-stopped

volumes:
  wallet_jenkins_home:
    driver: local
    driver_opts:
      type: none
      device: D:/wallet_clone/wallet/jenkins_home
      o: bind
  wallet_docker_data:
    driver: local
    driver_opts:
      type: none
      device: D:/wallet_clone/wallet/docker-data
      o: bind

networks:
  wallet-jenkins-network:
    driver: bridge 